# Generated by Django 5.2.10 on 2026-02-11 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0003_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_add_book', 'Can add book (custom)'), ('can_change_book', 'Can change book (custom)'), ('can_delete_book', 'Can delete book (custom)'))},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
    ]
